version: build{build}

branches:
        only:
                - master
                - dev

environment:
        matrix:
        - name: win32
          #                platform: amd64_x86
                qt: msvc2017

build_script:
#        - call ""
        - set QTDIR=D:\Qt\5.13.0\mingw73_64
        - set PATH=%PATH%;%QTDIR%\bin;
        - qmake
        - nmake & exit 0

